//! SearchAdvanced record type mapping for SOAP queries.
//!
//! Generated from NetSuite 2025.2 XSDs. Each entry represents a searchable record type,
//! mapping CLI name to XSI type and namespace.
//!
//! Generation note: grep complexType name="*SearchAdvanced" across:
//! https://webservices.netsuite.com/xsd/<module>/v2025_2_0/*.xsd
//! CLI name = lowercased XSI type minus "SearchAdvanced" suffix.
//! Namespace = XSD targetNamespace.

pub struct SearchType {
    pub xsi_type: &'static str,
    pub namespace: &'static str,
}

/// Complete mapping of 95 searchable record types from NetSuite 2025.2 WSDL.
const SEARCH_TYPES: &[(&str, &str, &str)] = &[
    (
        "account",
        "AccountSearchAdvanced",
        "urn:accounting_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "accountingperiod",
        "AccountingPeriodSearchAdvanced",
        "urn:accounting_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "accountingtransaction",
        "AccountingTransactionSearchAdvanced",
        "urn:sales_2025_2.transactions.webservices.netsuite.com",
    ),
    (
        "billingaccount",
        "BillingAccountSearchAdvanced",
        "urn:relationships_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "billingschedule",
        "BillingScheduleSearchAdvanced",
        "urn:accounting_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "bin",
        "BinSearchAdvanced",
        "urn:accounting_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "bom",
        "BomSearchAdvanced",
        "urn:accounting_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "bomrevision",
        "BomRevisionSearchAdvanced",
        "urn:accounting_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "budget",
        "BudgetSearchAdvanced",
        "urn:financial_2025_2.transactions.webservices.netsuite.com",
    ),
    (
        "calendarevent",
        "CalendarEventSearchAdvanced",
        "urn:scheduling_2025_2.activities.webservices.netsuite.com",
    ),
    (
        "campaign",
        "CampaignSearchAdvanced",
        "urn:marketing_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "charge",
        "ChargeSearchAdvanced",
        "urn:customers_2025_2.transactions.webservices.netsuite.com",
    ),
    (
        "classification",
        "ClassificationSearchAdvanced",
        "urn:accounting_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "consolidatedexchangerate",
        "ConsolidatedExchangeRateSearchAdvanced",
        "urn:accounting_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "contact",
        "ContactSearchAdvanced",
        "urn:relationships_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "contactcategory",
        "ContactCategorySearchAdvanced",
        "urn:accounting_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "contactrole",
        "ContactRoleSearchAdvanced",
        "urn:accounting_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "costcategory",
        "CostCategorySearchAdvanced",
        "urn:accounting_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "couponcode",
        "CouponCodeSearchAdvanced",
        "urn:marketing_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "currencyrate",
        "CurrencyRateSearchAdvanced",
        "urn:accounting_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "customer",
        "CustomerSearchAdvanced",
        "urn:relationships_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "customercategory",
        "CustomerCategorySearchAdvanced",
        "urn:accounting_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "customermessage",
        "CustomerMessageSearchAdvanced",
        "urn:accounting_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "customerstatus",
        "CustomerStatusSearchAdvanced",
        "urn:relationships_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "customersubsidiaryrelationship",
        "CustomerSubsidiaryRelationshipSearchAdvanced",
        "urn:relationships_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "customlist",
        "CustomListSearchAdvanced",
        "urn:customization_2025_2.setup.webservices.netsuite.com",
    ),
    (
        "customrecord",
        "CustomRecordSearchAdvanced",
        "urn:customization_2025_2.setup.webservices.netsuite.com",
    ),
    (
        "department",
        "DepartmentSearchAdvanced",
        "urn:accounting_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "employee",
        "EmployeeSearchAdvanced",
        "urn:employees_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "entitygroup",
        "EntityGroupSearchAdvanced",
        "urn:relationships_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "expensecategory",
        "ExpenseCategorySearchAdvanced",
        "urn:accounting_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "fairvalueprice",
        "FairValuePriceSearchAdvanced",
        "urn:accounting_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "file",
        "FileSearchAdvanced",
        "urn:filecabinet_2025_2.documents.webservices.netsuite.com",
    ),
    (
        "folder",
        "FolderSearchAdvanced",
        "urn:filecabinet_2025_2.documents.webservices.netsuite.com",
    ),
    (
        "giftcertificate",
        "GiftCertificateSearchAdvanced",
        "urn:accounting_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "globalaccountmapping",
        "GlobalAccountMappingSearchAdvanced",
        "urn:accounting_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "hcmjob",
        "HcmJobSearchAdvanced",
        "urn:employees_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "inboundshipment",
        "InboundShipmentSearchAdvanced",
        "urn:purchases_2025_2.transactions.webservices.netsuite.com",
    ),
    (
        "inventorynumber",
        "InventoryNumberSearchAdvanced",
        "urn:accounting_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "issue",
        "IssueSearchAdvanced",
        "urn:support_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "item",
        "ItemSearchAdvanced",
        "urn:accounting_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "itemaccountmapping",
        "ItemAccountMappingSearchAdvanced",
        "urn:accounting_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "itemdemandplan",
        "ItemDemandPlanSearchAdvanced",
        "urn:demandplanning_2025_2.transactions.webservices.netsuite.com",
    ),
    (
        "itemrevision",
        "ItemRevisionSearchAdvanced",
        "urn:accounting_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "itemsupplyplan",
        "ItemSupplyPlanSearchAdvanced",
        "urn:demandplanning_2025_2.transactions.webservices.netsuite.com",
    ),
    (
        "job",
        "JobSearchAdvanced",
        "urn:relationships_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "jobstatus",
        "JobStatusSearchAdvanced",
        "urn:relationships_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "jobtype",
        "JobTypeSearchAdvanced",
        "urn:relationships_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "location",
        "LocationSearchAdvanced",
        "urn:accounting_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "manufacturingcosttemplate",
        "ManufacturingCostTemplateSearchAdvanced",
        "urn:supplychain_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "manufacturingoperationtask",
        "ManufacturingOperationTaskSearchAdvanced",
        "urn:supplychain_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "manufacturingrouting",
        "ManufacturingRoutingSearchAdvanced",
        "urn:supplychain_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "merchandisehierarchynode",
        "MerchandiseHierarchyNodeSearchAdvanced",
        "urn:accounting_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "message",
        "MessageSearchAdvanced",
        "urn:communication_2025_2.general.webservices.netsuite.com",
    ),
    (
        "nexus",
        "NexusSearchAdvanced",
        "urn:accounting_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "note",
        "NoteSearchAdvanced",
        "urn:communication_2025_2.general.webservices.netsuite.com",
    ),
    (
        "notetype",
        "NoteTypeSearchAdvanced",
        "urn:accounting_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "opportunity",
        "OpportunitySearchAdvanced",
        "urn:sales_2025_2.transactions.webservices.netsuite.com",
    ),
    (
        "othernamecategory",
        "OtherNameCategorySearchAdvanced",
        "urn:accounting_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "partner",
        "PartnerSearchAdvanced",
        "urn:relationships_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "partnercategory",
        "PartnerCategorySearchAdvanced",
        "urn:accounting_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "paycheck",
        "PaycheckSearchAdvanced",
        "urn:employees_2025_2.transactions.webservices.netsuite.com",
    ),
    (
        "paymentinstrument",
        "PaymentInstrumentSearchAdvanced",
        "urn:accounting_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "paymentmethod",
        "PaymentMethodSearchAdvanced",
        "urn:accounting_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "paymentoption",
        "PaymentOptionSearchAdvanced",
        "urn:accounting_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "payrollitem",
        "PayrollItemSearchAdvanced",
        "urn:employees_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "phonecall",
        "PhoneCallSearchAdvanced",
        "urn:scheduling_2025_2.activities.webservices.netsuite.com",
    ),
    (
        "pricelevel",
        "PriceLevelSearchAdvanced",
        "urn:accounting_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "pricinggroup",
        "PricingGroupSearchAdvanced",
        "urn:accounting_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "projecttask",
        "ProjectTaskSearchAdvanced",
        "urn:scheduling_2025_2.activities.webservices.netsuite.com",
    ),
    (
        "promotioncode",
        "PromotionCodeSearchAdvanced",
        "urn:marketing_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "resourceallocation",
        "ResourceAllocationSearchAdvanced",
        "urn:scheduling_2025_2.activities.webservices.netsuite.com",
    ),
    (
        "revrecschedule",
        "RevRecScheduleSearchAdvanced",
        "urn:accounting_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "revrectemplate",
        "RevRecTemplateSearchAdvanced",
        "urn:accounting_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "salesrole",
        "SalesRoleSearchAdvanced",
        "urn:accounting_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "salestaxitem",
        "SalesTaxItemSearchAdvanced",
        "urn:accounting_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "sitecategory",
        "SiteCategorySearchAdvanced",
        "urn:website_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "solution",
        "SolutionSearchAdvanced",
        "urn:support_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "subsidiary",
        "SubsidiarySearchAdvanced",
        "urn:accounting_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "supportcase",
        "SupportCaseSearchAdvanced",
        "urn:support_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "task",
        "TaskSearchAdvanced",
        "urn:scheduling_2025_2.activities.webservices.netsuite.com",
    ),
    (
        "taxgroup",
        "TaxGroupSearchAdvanced",
        "urn:accounting_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "taxtype",
        "TaxTypeSearchAdvanced",
        "urn:accounting_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "term",
        "TermSearchAdvanced",
        "urn:accounting_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "timebill",
        "TimeBillSearchAdvanced",
        "urn:employees_2025_2.transactions.webservices.netsuite.com",
    ),
    (
        "timeentry",
        "TimeEntrySearchAdvanced",
        "urn:employees_2025_2.transactions.webservices.netsuite.com",
    ),
    (
        "timesheet",
        "TimeSheetSearchAdvanced",
        "urn:employees_2025_2.transactions.webservices.netsuite.com",
    ),
    (
        "topic",
        "TopicSearchAdvanced",
        "urn:support_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "transaction",
        "TransactionSearchAdvanced",
        "urn:sales_2025_2.transactions.webservices.netsuite.com",
    ),
    (
        "unitstype",
        "UnitsTypeSearchAdvanced",
        "urn:accounting_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "usage",
        "UsageSearchAdvanced",
        "urn:sales_2025_2.transactions.webservices.netsuite.com",
    ),
    (
        "vendor",
        "VendorSearchAdvanced",
        "urn:relationships_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "vendorcategory",
        "VendorCategorySearchAdvanced",
        "urn:accounting_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "vendorsubsidiaryrelationship",
        "VendorSubsidiaryRelationshipSearchAdvanced",
        "urn:relationships_2025_2.lists.webservices.netsuite.com",
    ),
    (
        "winlossreason",
        "WinLossReasonSearchAdvanced",
        "urn:accounting_2025_2.lists.webservices.netsuite.com",
    ),
];

pub fn lookup(record_type: &str) -> Option<SearchType> {
    let wanted = record_type.to_ascii_lowercase();
    SEARCH_TYPES
        .iter()
        .find(|(cli_name, _, _)| *cli_name == wanted)
        .map(|(_, xsi_type, namespace)| SearchType {
            xsi_type,
            namespace,
        })
}

pub fn known_type_names() -> String {
    SEARCH_TYPES
        .iter()
        .map(|(cli_name, _, _)| *cli_name)
        .collect::<Vec<_>>()
        .join(", ")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lookup_maps_cli_names_to_xsi_types_and_namespaces() {
        let transaction = lookup("transaction").expect("known type");
        assert_eq!(transaction.xsi_type, "TransactionSearchAdvanced");
        assert_eq!(
            transaction.namespace,
            "urn:sales_2025_2.transactions.webservices.netsuite.com"
        );

        let custom = lookup("CustomRecord").expect("case-insensitive");
        assert_eq!(custom.xsi_type, "CustomRecordSearchAdvanced");
        assert_eq!(
            custom.namespace,
            "urn:customization_2025_2.setup.webservices.netsuite.com"
        );

        assert!(lookup("nonsense").is_none());
        assert_eq!(SEARCH_TYPES.len(), 95);
    }

    #[test]
    fn known_type_names_lists_all_alphabetically() {
        let names = known_type_names();
        assert!(names.starts_with("account, accountingperiod"));
        assert!(names.ends_with("winlossreason"));
    }
}
